import {mountNavbar} from '../components/navbar.js';import {mountFooter} from '../components/footer.js';import {mountLoader} from '../components/loader.js';import {initAnimations,beltUnlock} from '../components/animations.js';import {api,demoFighters,demoEvents} from '../components/api.js';import {toast} from '../components/toast.js';
mountLoader();await mountNavbar('home');mountFooter();initAnimations();
let fighters=demoFighters,events=demoEvents;try{const [fd,ed]=await Promise.all([api('/fighters?limit=20'),api('/events')]);fighters=fd.fighters?.length?fd.fighters.map(n):demoFighters;events=ed.tournaments?.length?ed.tournaments:demoEvents}catch{toast('Backend offline: using demo data','info')}
document.querySelector('#heroFighters').textContent=fighters.length;document.querySelector('#heroEvents').textContent=events.length;const ticker=['Live ticker: Makhachev pressure index rising','Aspinall speed metrics shock heavyweight division','Nexus PPV countdown active','Admin analytics synced','Press T to cycle arena themes'];tickerTrack.innerHTML=[...ticker,...ticker].map(t=>`<div><span>●</span> ${t}</div>`).join('');
featuredCarousel.innerHTML=fighters.map(f=>`<article class="arena-card feature-card fighter-card" data-parallax><img src="${f.image}" alt="${f.name}"><div><span class="badge ${f.champion?'gold':''}">${f.champion?'Champion':f.division}</span><h3>${f.name}</h3><p class="muted">${f.division} • ${f.country}</p><div class="card-stats"><span>${f.wins} W</span><span>${f.losses} L</span><span>${f.ko} KO</span><span>${f.reach}</span></div></div></article>`).join('');
timeline.innerHTML=[['1993','UFC 1','The first tournament changed combat sports forever.'],['2015','Rise of Conor','Star power, movement and precision striking.'],['2018','Khabib Era','Unbeaten dominance became the pressure standard.'],['2023+','Islam Era','Modern sambo and championship grappling.'],['Next','UFC Nexus','Dynamic events, rankings, payments and profiles.']].map(([y,t,d])=>`<div class="arena-card timeline-item card-pad"><span class="badge red">${y}</span><h3>${t}</h3><p class="muted">${d}</p></div>`).join('');
eventsGrid.innerHTML=events.map(e=>`<article class="arena-card event-card"><div><span class="badge gold">${e.status||'Upcoming'}</span><h3 class="event-title">${e.title}</h3><p class="muted">${e.location}</p></div><div class="countdown" data-date="${e.date}"></div><a class="btn-primary" href="../tournaments/tournaments.html#register">Register</a></article>`).join('');tick();setInterval(tick,1000);
[simA,simB].forEach(s=>s.innerHTML=fighters.map(f=>`<option>${f.name}</option>`).join(''));simB.selectedIndex=1;simulateBtn.onclick=()=>{const a=fighters.find(f=>f.name===simA.value),b=fighters.find(f=>f.name===simB.value);if(a.name===b.name)return toast('Pick two different fighters','error');const sa=a.wins*2+a.ko+a.submissions+Math.random()*20-a.losses,sb=b.wins*2+b.ko+b.submissions+Math.random()*20-b.losses,w=sa>=sb?a:b;const m=['KO/TKO','Submission','Decision','Doctor Stoppage'][Math.floor(Math.random()*4)];simResult.innerHTML=`<h3 class="event-title">${w.name}</h3><p class="muted">wins by ${m}. Arena confidence ${(Math.max(sa,sb)*1.7).toFixed(0)}%</p>`;beltUnlock(`${w.name} highlight unlocked`)};
function tick(){document.querySelectorAll('.countdown').forEach(box=>{const diff=Math.max(0,new Date(box.dataset.date)-new Date());box.innerHTML=`<b>${Math.floor(diff/86400000)}<small>d</small></b><b>${Math.floor(diff/3600000)%24}<small>h</small></b><b>${Math.floor(diff/60000)%60}<small>m</small></b>`})}function n(f){return{...f,image:f.image?.startsWith('/assets')?'..'+f.image:f.image}}
