services:
  - type: web
    name: ufc-nexus-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
