import {mountNavbar} from '../components/navbar.js';import {mountFooter} from '../components/footer.js';import {mountLoader} from '../components/loader.js';import {initAnimations,beltUnlock} from '../components/animations.js';import {api,demoFighters,storage} from '../components/api.js';import {toast} from '../components/toast.js';
mountLoader();await mountNavbar('fighters');mountFooter();initAnimations();let fighters=demoFighters,page=1,state={search:'',division:'All',country:'All',status:'All',sort:'rank'};
try{const d=await api('/fighters?limit=50');fighters=d.fighters?.length?d.fighters.map(f=>({...f,image:f.image?.startsWith('/assets')?'..'+f.image:f.image})):demoFighters}catch{toast('Backend offline: using demo fighters','info')}
fill(division,['All',...new Set(fighters.map(f=>f.division))]);fill(country,['All',...new Set(fighters.map(f=>f.country))]);['search','division','country','status','sort'].forEach(id=>document.getElementById(id).oninput=e=>{state[id]=e.target.value;page=1;render()});fighterModal.onclick=e=>{if(e.target.id==='fighterModal'||e.target.closest('.close-modal'))fighterModal.classList.remove('show')};render();
function fill(el,arr){el.innerHTML=arr.map(v=>`<option value="${v}">${v}</option>`).join('')}function list(){return fighters.filter(f=>`${f.name} ${f.country} ${f.division}`.toLowerCase().includes(state.search.toLowerCase())&&(state.division==='All'||f.division===state.division)&&(state.country==='All'||f.country===state.country)&&(state.status==='All'||(state.status==='Champion'?f.champion:f.status===state.status))).sort((a,b)=>state.sort==='highestWins'?b.wins-a.wins:state.sort==='accuracy'?b.accuracy-a.accuracy:state.sort==='recent'?new Date(b.createdAt||0)-new Date(a.createdAt||0):a.rank-b.rank)}
function render(){const per=8,filtered=list(),pages=Math.max(1,Math.ceil(filtered.length/per));page=Math.min(page,pages);playersGrid.innerHTML=filtered.slice((page-1)*per,page*per).map(card).join('')||'<p class="muted">No fighters found.</p>';document.querySelectorAll('.player-card').forEach(el=>el.onclick=()=>openModal(fighters.find(f=>f.name===el.dataset.name)));pagination.innerHTML=`<button class="btn-ghost" id="prev" ${page===1?'disabled':''}>Prev</button><span class="badge">Page ${page} / ${pages}</span><button class="btn-ghost" id="next" ${page===pages?'disabled':''}>Next</button>`;prev.onclick=()=>{page--;render()};next.onclick=()=>{page++;render()}}
function card(f){return`<article class="arena-card player-card fighter-card" data-name="${f.name}"><img src="${f.image}" alt="${f.name}"><div><span class="badge ${f.champion?'gold':''}">${f.champion?'Champion':f.status}</span><h3>${f.name}</h3><p class="muted">${f.division} • ${f.country}</p><div class="player-meta"><span class="badge">${f.wins}-${f.losses}</span><span class="badge">Reach ${f.reach}</span><span class="badge">${f.weight}</span></div></div></article>`}
function openModal(f){const saved=JSON.parse(localStorage.getItem('ufc-favorites')||'[]').includes(f.name);modalContent.innerHTML=`<img src="${f.image}" alt="${f.name}"><div class="modal-body"><button class="btn-ghost close-modal">Close</button><span class="badge ${f.champion?'gold':''}">${f.champion?'Champion':f.division}</span><h2>${f.name}</h2><p class="muted">${f.bio||'Elite mixed martial artist.'}</p><div class="stat-grid"><div class="stat"><strong>${f.wins}</strong><span>Wins</span></div><div class="stat"><strong>${f.losses}</strong><span>Losses</span></div><div class="stat"><strong>${f.ko}</strong><span>KO</span></div><div class="stat"><strong>${f.reach}</strong><span>Reach</span></div></div><p><b>Style:</b> ${f.style||'MMA'}</p><button class="btn-primary" id="saveFav">${saved?'Remove favorite':'Save fighter'}</button></div>`;fighterModal.classList.add('show');saveFav.onclick=()=>saveFavorite(f)}
async function saveFavorite(f){const set=new Set(JSON.parse(localStorage.getItem('ufc-favorites')||'[]'));set.has(f.name)?set.delete(f.name):set.add(f.name);localStorage.setItem('ufc-favorites',JSON.stringify([...set]));if(storage.user?._id&&f._id)try{await api(`/users/${storage.user._id}/favorites/${f._id}`,{method:'POST'})}catch{}toast(set.has(f.name)?'Fighter saved':'Favorite removed','success');if(set.size>=3)beltUnlock('Collector Belt Unlocked');fighterModal.classList.remove('show')}
