import {mountNavbar} from '../components/navbar.js';import {mountFooter} from '../components/footer.js';import {mountLoader} from '../components/loader.js';import {initAnimations} from '../components/animations.js';import {api,currentUser,API_BASE} from '../components/api.js';import {toast} from '../components/toast.js';
mountLoader();await mountNavbar('admin');mountFooter();initAnimations();const user=await currentUser();if(!user||user.role!=='admin')location.href='../auth/login.html';
const resources={users:{endpoint:'/users',fields:['name','email','role','theme'],create:false},fighters:{endpoint:'/fighters',fields:['name','division','country','wins','losses','ko','submissions','reach','weight','rank','champion','status','image']},events:{endpoint:'/events',fields:['title','subtitle','date','location','arena','seats','fee','status']},registrations:{endpoint:'/events/registrations',fields:['name','email','age','seatType','approvalStatus'],create:false},payments:{endpoint:'/payments',fields:['amount','currency','status'],create:false},contacts:{endpoint:'/contact',fields:['name','email','phone','message','status'],create:false}};let active='fighters',cache=[],analytics={};await loadAnalytics();renderTabs();await loadResource();await loadActivity();
async function loadAnalytics(){try{analytics=(await api('/admin/analytics')).analytics}catch(e){toast(e.message,'error')}analytics.innerHTML;document.querySelector('#analytics').innerHTML=Object.entries(analytics).map(([k,v])=>`<div class="stat"><strong>${Number(v).toLocaleString()}</strong><span>${k}</span></div>`).join('');drawChart()}
function renderTabs(){adminTabs.innerHTML=Object.keys(resources).map(r=>`<button class="btn-ghost ${r===active?'active':''}" data-r="${r}">${r}</button>`).join('');adminTabs.querySelectorAll('button').forEach(b=>b.onclick=async()=>{active=b.dataset.r;renderTabs();await loadResource()})}
async function loadResource(){try{const d=await api(resources[active].endpoint);cache=d[active]||d.tournaments||d.registrations||d.payments||d.contacts||d.users||[];renderTable()}catch(e){toast(e.message,'error')}}
function renderTable(){const q=adminSearch.value?.toLowerCase()||'',rows=cache.filter(r=>JSON.stringify(r).toLowerCase().includes(q)),fields=resources[active].fields;addBtn.style.display=resources[active].create===false?'none':'inline-flex';adminTable.innerHTML=`<thead><tr>${fields.map(f=>`<th>${f}</th>`).join('')}<th>Actions</th></tr></thead><tbody>${rows.map(row=>`<tr>${fields.map(f=>`<td>${fmt(row[f])}</td>`).join('')}<td><button class="btn-ghost edit" data-id="${row._id}">Edit</button> <button class="btn-danger del" data-id="${row._id}">Delete</button></td></tr>`).join('')}</tbody>`;document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>openModal(cache.find(r=>r._id===b.dataset.id)));document.querySelectorAll('.del').forEach(b=>b.onclick=()=>del(b.dataset.id))}
function fmt(v){return Array.isArray(v)?v.length:typeof v==='boolean'?(v?'yes':'no'):v&&typeof v==='object'?(v.name||v.title||v.email||'object'):(v??'—')}
adminSearch.oninput=renderTable;addBtn.onclick=()=>openModal({});exportBtn.onclick=async()=>{try{const res=await fetch(`${API_BASE}/admin/export/${active}`,{headers:{Authorization:`Bearer ${localStorage.getItem('ufc-token')||sessionStorage.getItem('ufc-token')}`}});const blob=await res.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${active}.csv`;a.click();URL.revokeObjectURL(url)}catch(e){toast(e.message,'error')}};
function openModal(row){const fields=resources[active].fields,isEdit=!!row._id;crudForm.innerHTML=`<div class="full"><h2>${isEdit?'Edit':'Add'} ${active}</h2></div>${fields.map(f=>`<div><label>${f}</label><input name="${f}" class="arena-input" value="${row[f]??''}"></div>`).join('')}<button class="btn-primary full">Save</button><button class="btn-ghost full" type="button" id="closeCrud">Cancel</button>`;crudModal.classList.add('show');closeCrud.onclick=()=>crudModal.classList.remove('show');crudForm.onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(crudForm));['wins','losses','ko','submissions','rank','seats','fee','amount','age'].forEach(k=>{if(body[k]!==undefined&&body[k]!=='')body[k]=Number(body[k])});if(body.champion!==undefined)body.champion=['true','yes','1'].includes(String(body.champion));try{await api(`${resources[active].endpoint}${isEdit?`/${row._id}`:''}`,{method:isEdit?'PUT':'POST',body});toast('Record saved','success');crudModal.classList.remove('show');await loadResource();await loadAnalytics()}catch(err){toast(err.message,'error')}}}
async function del(id){if(!confirm('Delete this record?'))return;try{await api(`${resources[active].endpoint}/${id}`,{method:'DELETE'});toast('Record deleted','success');await loadResource();await loadAnalytics()}catch(e){toast(e.message,'error')}}
async function loadActivity(){try{const d=await api('/admin/activity');activityLogs.innerHTML=d.logs.map(l=>`<p class="badge">${l.action} ${l.resource} • ${new Date(l.createdAt).toLocaleString()}</p>`).join('')}catch{}}
function drawChart(){if(!window.Chart)return;new Chart(adminChart,{type:'doughnut',data:{labels:Object.keys(analytics),datasets:[{data:Object.values(analytics).map(Number)}]},options:{plugins:{legend:{labels:{color:'#fff'}}}}})}
